### ISSUE TITLE
TA suggestion: Requirement specifications

### ISSUE THREAD

**Issue by vppatel111** [CMPUT301F18T24/Mark-Me#4]
We need more exceptions for whenever we are loading something, we should ask "what if it fails to load" and provide an alternate flow, for each relevant use case.

For example, there are no exceptions for if the locations fail to load properly.

**Comment by rizwan146** [comment]
added exceptions to 2. PatientDeleteProblem (US 01.04.01)

**Comment by rizwan146** [comment]
added exceptions to 4. PatientViewsListOfProblems (US 01.02.01)

**Comment by rizwan146** [comment]
added execptions to 7. PatientSpecifiesBodyLocationForRecord (02.04.01)

**Comment by rizwan146** [comment]
added exceptions to 10. PatientGetsExampleOfHowToTakePhoto (02.09.01)

**Comment by rizwan146** [comment]
added exceptions to 14. PatientCareProviderViewContactInformation (US 03.03.01)

**Comment by rizwan146** [comment]
added exceptions to 18. PatientCareProviderViewRecordLocation (US 10.02.01)

**Comment by rizwan146** [comment]
added exceptions to 19. PatientCareProviderViewAllRecordLocations (US 10.03.01)

**Comment by rizwan146** [comment]
22. CareProviderAddPatient(US 07.01.01)

**Comment by rizwan146** [comment]
added exceptions to 24. CareProviderViewsPatientsList (US 06.01.01)

**Comment by rizwan146** [comment]
added exceptions to 25. SearchProblemOrRecordsByKeywords (US 04.01.01)

**Comment by rizwan146** [comment]
added exceptions to 26. SearchProblemOrRecordByKeywordNearGeoLocation (US 04.02.01)

**Comment by rizwan146** [comment]
All the major uses cases now have exceptions.
